### ISSUE TITLE
A stupid vega-lite question

### ISSUE THREAD

**Issue by aborruso** [sirselim/covid_analysis#3]
First of all you have made a great job, I'm using it to learn a little to use vega-lite.

In [this chart](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MAA4ADMfURIKRtXwGATAFYzGyIXQ6djJdQMPzUHWQEACdGQjweFRxIWEZUQjFkMCpacUkwJHRgvDBtFjAJJQBrZB0wHXQ8TH9ICLxEg0gAYVZUVjFKxioM5QAzRmDUUrAmgHkANQBJABEM9FggsC8wADkALTBpgAkAIVg1Fwqqg1AIC1ZgsUb8IhJyYPRNBmY2dlYF4PhlPGQlPDovqg+AMFhIgV8KLoAProJToMQAT1isFIGFgP2CpCO6FI6zGU2mUK+Sn6g1KUN63EGlR+OnkihUGgAvjU8A8lLBKYMDABtDQQU5nCyKbK84CQfrIMQ6RrTSpJbi9MDBZCEKl4SBMgC6-iFkG0Sh03E0Ysg3EIjS+rD+aigkullu41o1qig80trXanSoRKdNu1urOEoeQ15SnaYldxi1-LATI0OpcGGCRROtQRhGQjXYWVttW43DEEQtODZrGQLJcvy+nm8J1jkAAHmn7TLonKfmBFcrVeq83gM1nokpuKgvPDNYHIAiW4wpW2oPBPR0Ij6rTbXenM40AI6sWF1b1Zyt6r5iKn1oUWCjw8uNdHIKXsMR3wMWYmeCLKS9Xiw-dGzvOsryl2SoqmqoqbtQPyNHYxhwSIxgAMwiHYABsk6xnqN4vkOUBUrC1BZlhcaxvGEDxkyQA) you have

```json
"transform": [
    {
      "sort": [{"field": "Date of report"}],
      "window": [{"op": "count", "field": "count", "as": "cumulative_count"}],
      "frame": [null, 0]
    }
  ]
```

You apply `count` op, to field `count` and you choose as output name `cumulative_count`. But in the [source data](https://raw.githubusercontent.com/sirselim/covid_analysis/master/data/NZCOVID_confirmed_formatted.json) there is not `count` field. 

The `cumulative_count` applies the count for each day. How vega-lite knows it has to do it and group by `Date of report`?

Thank you

**Comment by sirselim** [comment]
Thanks for taking an interest and providing this feedback. Not a stupid question at all, it's a good catch!

It's actually just redundant as the `field` variable assigned in the `sort` is the one being used, so deleting `"field": "count"` doesn't do anything as it was not doing anything in the first place. So the count is being applied to the data provided in the sort function:

```java
"transform": [
    {
      "sort": [{"field": "Date of report"}],
      "window": [{"op": "count", "as": "cumulative_count"}],
      "frame": [null, 0]
    }
  ]
```
Thank you for pointing this out, I appreciate it. I myself am using this as a means to learn more about vega/vega-lite.

As an aside I am also working my way through the scripts to fix various other niggles. For one, I am now using the "temporal" type on any date data to better represent and format it, example: [link](https://vega.github.io/editor/?#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioAWegCs4PAHZQANOEhQA7kwAmrHGADsABlMbIeFExoEjAJgCsFzRChEMevU2U0jTpZaeiiIAE5MRPi8qrhQcExoROIoYNR0ElJgyBhh+GC6rGCSygDWKHpgehj4WEHu0fgpRlAAwmxobOI1TNTZKgBmTGFoFWCtAPIAagCSACLZGHChYL5gAHIAWmBzABIAQnDqbtDVtUagVu5sYeItBMSkFGEY2ows7Bxsy2EIKvgoZT4eh-ND8YbLSRgv6UfQAfQwygw4gAngk4GRMHAAWEyGcMGQtpNZnM4X9lEMRhU4QMeCMagC9AolKoTgBferQfAvZRwWkjIwAbUuV3idPwQuA0CGKHEehacxqqR4AzAYRQRHFUDAbIAupz3LplHoeNpJdAeEQWn82ED1NAltaOl0etQyTxbRKdfqTu4Bi9RkLlF1xGowKZdeyfVYoJgwqULr6uSiiCgWhxcscrlyeDxxNErbhuWwUOzOVBAX8fH5E9moAAPWvZ6VMWXyuKKgFgFVqjVag1afAptNxAFJOnIrPNqDRUYAVWULBaaH+SGqKKndYzxqMpnoADYkxyk1AN7gRXWZXKnZ1utE3Ta7QOGsOWgBHNiIxqutNHgdQP5xDpJs60oZESxabEUFlDhxAg59oHJHxohUEDpwBbELjAJNL1ba8OyVbtVXVTU8ntHDRRoAE0ObLQURQTNcAcUxmLDCi6xXIEkGXTM2NouszhHMAHEPfirjZdjIGPMSoDAuChKgCc-F-WiJOzNSpM0NkgA)

Cheers
